/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a3_edmondliang;

/**
 *
 * @author edmon
 */
public class U1A3_EdmondLiang extends javax.swing.JFrame {

    /**
     * Creates new form U1A3_EdmondLiang
     */
    public U1A3_EdmondLiang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtgetscale = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblHurricaneCategory = new javax.swing.JLabel();
        lblCategorySpeed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setText("Hurricane Scale");

        lbl2.setText("Please enter a hurricabe category(1-5): ");

        txtgetscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetscaleActionPerformed(evt);
            }
        });

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbl1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHurricaneCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtgetscale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(lblCategorySpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(txtgetscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblHurricaneCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategorySpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgetscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetscaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgetscaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Attempt to parse the text entered in txtgetscale as an integer
            int category=Integer.parseInt(txtgetscale.getText());
            
            // Use a switch statement to determine the hurricane category based on the entered number
            switch(category) {
                // Display information for Category 1 hurricane
                case 1:
                    lblHurricaneCategory.setText("wind seed for category 1 is:");
                    lblCategorySpeed.setText("74-95 mph or 64-82 kt or 119-153 km/hr");
                    break;
                    
                // Display information for Category 2 hurricane
                case 2:
                    lblHurricaneCategory.setText("wind speed for category 2 is:");
                    lblCategorySpeed.setText("96-110 mph or 83-95 kt or 154-177 km/hr");
                    break;
                    
                // Display information for Category 3 hurricane
                case 3:
                    lblHurricaneCategory.setText("wind speedforcategory 3 is:");
                    lblCategorySpeed.setText("111-130 mph or 96-113 kt or 178-209 km/hr");
                    break;
                    
                // Display information for Category 4 hurricane
                case 4:
                    lblHurricaneCategory.setText("wind speed for category 4 is:");
                    lblCategorySpeed.setText("131-155 mph or 114-135 kt or 210-249 km/hr");
                    break;
                    
                // Display information for Category 5 hurricane
                case 5:
                    lblHurricaneCategory.setText("wind speed for category 5 is:");
                    lblCategorySpeed.setText("greater than 155 mph or 135 kt or 249 km/hr");
                    break;
                    
                // Display an error message if the entered number is not within 1-5
                default:
                    lblHurricaneCategory.setText("error");
                    lblCategorySpeed.setText("please enter a valid number");
        }
        }
        catch (Exception e) {
            // Handle exceptions if the input cannot be parsed as an integer
            lblHurricaneCategory.setText("error");
            lblCategorySpeed.setText("please enter a number");
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A3_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A3_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A3_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A3_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A3_EdmondLiang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblCategorySpeed;
    private javax.swing.JLabel lblHurricaneCategory;
    private javax.swing.JTextField txtgetscale;
    // End of variables declaration//GEN-END:variables
}
